name = "docker-registry-cf"
main = "src/index.ts"
workers_dev = false
compatibility_date = "2023-06-04"
send_metrics = false

[[r2_buckets]]
binding = 'REGISTRY'
bucket_name = 'registry'
preview_bucket_name = 'registry-preview'